/* Zach Sadler
 * zaxcoding@gmail.com
 * Problem 29
 * How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
 */
 
import java.math.*;
import java.util.*;

public class problem29
{ 
	public static void main(String [] args)
	{
		PriorityQueue<BigInteger> list = new PriorityQueue<BigInteger>(100); 
		BigInteger exp, x;
		
		for (Integer a = 2; a <= 100; a++)
		{
			for (int b = 2; b <= 100; b++)
			{
				x = new BigInteger(a.toString());
				exp = x.pow(b);
				if (!list.contains(exp))
					list.add(exp);
			}
		}
		System.out.println(list.size());
	}
}